### ISSUE TITLE
Cannot open recorded video from grid extras node page when running on docker

### ISSUE THREAD

**Issue by lgermani** [viltgroup/docker-selenium-grid-extras#2]
Hello, 

I'm running some tests using docker-selenium-grid-extras, test execution run without a problem, but if you try to view or download the test recording video, nothing happens. 

I recorded what happens to the attached gif:
![sel-grid-extras-docker](https://user-images.githubusercontent.com/1315828/35449966-bf4f1b4e-02a5-11e8-9967-d853ee0a8a6b.gif)

**Comment by mariolameiras** [comment]
It looks like it timed out, can you try right clicking and saving the video to your desktop?

**Comment by lgermani** [comment]
@mariolameiras, same behavior when trying to save the video by right clicking and saving.

![sel-grid-extras-docker2](https://user-images.githubusercontent.com/1315828/35454889-f96d0726-02b6-11e8-903f-1e487cce4d15.gif)

**Comment by mariolameiras** [comment]
I'm not able to replicate your problem. Have you tried smaller or older videos?

Also, change your logs to info and checkout the logs inside /opt/selenium/log

**Comment by lgermani** [comment]
Same problem with small videos.

Changed to debug logs:
```
environment:
      - SE_OPTS=-debug true
```
After executing a small test, the video is generated inside video_output folder inside the container.
But I'm still unable to access it via Node Configuration page.

Here is the log:
[logs.zip](https://github.com/viltgroup/docker-selenium-grid-extras/files/1674798/logs.zip)

Onlything i see different from normal at the hub grid_extras log is:

```
29 Jan 2018 18:34:00 [Forwarding ext. key eaf37de159c37f8a696d51e2dc60a8bb to http://172.18.0.3:5555/wd/hub at 6:34:00 PM] INFO  video.RemoteVideoRecordingControlCallable  - Creating new Video callable for proxy: http://172.18.0.3:5555, int key: 26841487-09a7-4e95-8ff8-3e650434998a, ex. key: eaf37de159c37f8a696d51e2dc60a8bb, action: heartbeat, lastAction: get: {"url":"https://staging06-financeiro.hostgator.com.br"}
29 Jan 2018 18:34:00 [pool-1-thread-2] ERROR videorecording.RemoteVideoRecorderHelper  - Error building URI for host: 172.18.0.3, port: 3000, session: eaf37de159c37f8a696d51e2dc60a8bb, action: heartbeat, params: {session=eaf37de159c37f8a696d51e2dc60a8bb, action=heartbeat, description=get: {"url":"https://staging06-financeiro.hostgator.com.br"}}
java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:851)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:848)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequest(HttpUtility.java:60)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:35)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:29)
	at com.groupon.seleniumgridextras.utilities.HttpUtility.getRequestAsString(HttpUtility.java:25)
	at com.groupon.seleniumgridextras.videorecording.RemoteVideoRecorderHelper.updateLastAction(RemoteVideoRecorderHelper.java:109)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.updateLastAction(RemoteVideoRecordingControlCallable.java:112)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:65)
	at com.groupon.seleniumgridextras.utilities.threads.video.RemoteVideoRecordingControlCallable.call(RemoteVideoRecordingControlCallable.java:11)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
